version: 2

defaults: &defaults
  working_directory: ~/qsSimpleKPI
  docker:
    - image: circleci/node:stretch

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build and package
          command: |
            npm install
            ./scripts/bump-version.sh
            npm run build
      - persist_to_workspace:
          root: ~/qsSimpleKPI
          paths:
            - VERSION
            - deploy
  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/qsSimpleKPI
      - run:
          command: |
            pwd
            echo "Zip contents:"
            ls -l deploy
            VERSION="$(scripts/print-version.sh)"
            scripts/install-ghr.sh
            $HOME/bin/ghr -t ${ghoauth} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./deploy/qsSimpleKPI.zip
            ./scripts/persist-version.sh
workflows:
  version: 2
  master_flow:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - build_pipeline