version: 2

defaults: &defaults
  working_directory: ~/qsSimpleKPI
  docker:
    - image: circleci/node:stretch

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build and package
          command: |
            mkdir -p workspace
            echo "Hello, world!" > echo-output
            npm install
            ./scripts/bumpVersion.sh
            npm run build
          persist_to_workspace:
            root: ~/qsSimpleKPI
            paths:
              - VERSION
              - deploy
              - echo-output
  deploy:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Create GitHub release
          attach_workspace:
            at: ~/qsSimpleKPI
          command: |
            pwd
            ls -l
            MAJOR=$(grep -i 'MAJOR' VERSION  | cut -f2 -d'=')
            MINOR=$(grep -i 'MINOR' VERSION  | cut -f2 -d'=')
            PATCH=$(grep -i 'PATCH' VERSION  | cut -f2 -d'=')
            VERSION="${MAJOR}.${MINOR}.${PATCH}"
            echo ${VERSION}
            scripts/install-ghr.sh
            $HOME/bin/ghr -t ${ghoauth} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./deploy/qsSimpleKPI.zip
            ./scripts/persistVersion.sh
workflows:
  version: 2
  master_flow:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - build_pipeline