version: 2
jobs:
  build:
    docker:
      - image: circleci/node:stretch

    steps:
      - checkout
      - run:
          name: Build and package
          command: |
            npm install
            npm run build
          persist_to_workspace:
            root: /tmp/workspace
            paths:
              - deploy
      - run:
          name: Create GitHub release
          requires:
            - build
          attach_workspace:
            at: /tmp/workspace
          command: |
            ls -l deploy
            scripts/install-ghr.sh
            VERSION=$(cat version)
            $HOME/bin/ghr -t ${ghoauth} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./deploy/qsSimpleKPI.zip
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
