version: 2
jobs:
  build:
    docker:
      - image: circleci/node:stretch
    environment:
      GITHUB_TOKEN: "e9eb3ff59cbf68101948ba2fe06a7d350bfbfae9"
    steps:
      - checkout
      - run:
          name: Build and package
          command: |
            npm install
            npm run build
          persist_to_workspace:
            root: /tmp/workspace
            paths:
              - deploy
      - run:
          name: Create GitHub release
          attach_workspace:
            at: /tmp/workspace
          command: |
            ls -l deploy
            scripts/install-ghr.sh
            VERSION=$(cat version)
            $HOME/bin/ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./deploy/qsSimpleKPI.zip
